### ISSUE TITLE
GotoDocumentation not working on XP, 8 and Mavericks.

### ISSUE THREAD

**Issue by ghost** [kemayo/sublime-text-2-goto-documentation#41] opened 2014-08-05 18:09 UTC
Hi, I've tried to install the plugin using Package Manager or downloading to the Packages folder on Windows XP, Windows 8.1 and OSx Mavericks 10.9.4 but in all OSes using keyboard shortcuts or CMD+SHIFT+P > Goto Documentation (OSx) or CTRL+SHIFT+P > Goto Documentation (Windows) the plugin only opens Google (fallback_scope), I've tried with PHP, CSS and JS files and all extensions opens Google, if I change "fallback_scope" to "php" it always opens php.net.

Only fallback_scope are "working". I think that the problem is with scope detection, If I run on console
view.scope_name(view.sel()[0].begin()).rpartition('.')[2].strip() it detects the right scope.

**Comment by kemayo** [comment] 2014-08-05 19:41
Are you using ST2 or ST3?

**Comment by ghost** [comment] 2014-08-05 19:42
ST2

**Comment by kemayo** [comment] 2014-08-06 06:30
Okay, I can't reproduce this in ST2 or ST3 on Mavericks. I've tried PHP, CSS, JS, and Lua, and all worked correctly. (I even removed my normal git-checkout of the package and tried it with an installed from Package Control version.)

Could you try briefly disabling all other packages and seeing if you still have the problem?

**Comment by ghost** [comment] 2014-08-13 19:10
I tried on Linux (Lubuntu), ST2 with no other packages installed, and the same happens.
I tried on Windows 8.1 virtual machine with clean install of ST2, only GotoDocumentation installed with a simple PHP file and only google works too.

**Comment by ghost** [comment] 2014-08-13 19:35
Oh.. my mistake. I was always "selecting" the word that I want to go to docs. I tried only with cursor on that word and it works as expected. "Selecting" the word, google (fallback_scope) is loaded and with cursor blinking on that word the right scope (php, css, etc) opens.

I read "How to use" section on Github page and this behaviour was not clear to me. I think that you can explain a little better how this little difference (selected word vs current word in cursor) affects the scope that will be opened and this way other new "gotodocumentation" users have no difficulties to use for the first time.

Thank you.

**Comment by kemayo** [comment] 2014-08-13 23:30
Thanks for tracking that down! I've just committed 37eeab5 that should make it work whether you're selecting the text or just have your cursor in it.

**Closed as completed by kemayo** 2014-08-13 23:30 UTC
